/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LaunchpadPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// BookmarkStore.ts
var import_obsidian = require("obsidian");
var DEFAULT_BOOKMARKS_FILE = "bookmarks.md";
var BOOKMARK_RE = /^\s*-\s+\[(.+?)\]\((.+)\)\s*$/;
var ALLOWED_SCHEMES = ["https://", "http://", "obsidian://", "vault://", "note://"];
var FOLDER_SEP = "";
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function stripCtrl(s) {
  return s.replace(/[\x00-\x1f\x7f]/g, " ").trim();
}
var BookmarkStoreManager = class {
  constructor(app, filePath = DEFAULT_BOOKMARKS_FILE) {
    this.app = app;
    this.filePath = filePath;
  }
  getFilePath() {
    return this.filePath;
  }
  setFilePath(path) {
    this.filePath = path;
  }
  getFile() {
    if (!this.app.metadataCache)
      return null;
    const f = this.app.vault.getAbstractFileByPath(this.filePath);
    return f instanceof import_obsidian.TFile ? f : null;
  }
  /** Creates any missing parent folders for this.filePath. */
  async ensureParentFolders() {
    const dirs = this.filePath.split("/").slice(0, -1);
    if (dirs.length === 0)
      return;
    let current = "";
    for (const seg of dirs) {
      current = current ? `${current}/${seg}` : seg;
      const node = this.app.vault.getAbstractFileByPath(current);
      if (!node) {
        try {
          await this.app.vault.createFolder(current);
        } catch (e) {
        }
      }
    }
  }
  async ensureFile() {
    let f = this.getFile();
    if (!f) {
      try {
        const stat = await this.app.vault.adapter.stat(this.filePath);
        if (stat && stat.size > 0) {
          await sleep(600);
          f = this.getFile();
        }
      } catch (e) {
      }
    }
    if (!f) {
      await this.ensureParentFolders();
      await this.app.vault.create(this.filePath, "");
      f = this.getFile();
      if (!f) {
        throw new Error(
          `Bookmark Launcher: failed to create "${this.filePath}". Check that the path is valid and the vault is writable.`
        );
      }
    }
    return f;
  }
  async parse() {
    const maxAttempts = 5;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      const f = this.getFile();
      if (!f) {
        if (attempt < maxAttempts - 1) {
          await sleep(300 * Math.pow(2, attempt));
          continue;
        }
        return { folders: [], uncategorized: [] };
      }
      const content = await this.app.vault.read(f);
      if (content === "" && f.stat.size > 0) {
        if (attempt < maxAttempts - 1) {
          await sleep(300 * Math.pow(2, attempt));
          continue;
        }
        return { folders: [], uncategorized: [] };
      }
      return this.parseContent(content);
    }
    return { folders: [], uncategorized: [] };
  }
  parseContent(content) {
    const lines = content.split("\n");
    const store = { folders: [], uncategorized: [] };
    let currentFolder = null;
    let currentSubfolder = null;
    for (const line of lines) {
      if (line.startsWith("## ")) {
        const name = line.slice(3).trim();
        if (currentFolder) {
          currentSubfolder = { name, bookmarks: [], subfolders: [] };
          currentFolder.subfolders.push(currentSubfolder);
        } else {
          currentSubfolder = null;
          currentFolder = { name, bookmarks: [], subfolders: [] };
          store.folders.push(currentFolder);
        }
      } else if (line.startsWith("# ")) {
        const name = line.slice(2).trim();
        currentSubfolder = null;
        currentFolder = { name, bookmarks: [], subfolders: [] };
        store.folders.push(currentFolder);
      } else {
        const m = line.match(BOOKMARK_RE);
        if (m) {
          const parsedUrl = m[2];
          if (!ALLOWED_SCHEMES.some((s) => parsedUrl.startsWith(s))) {
            continue;
          }
          const bm = { name: m[1], url: parsedUrl };
          if (currentSubfolder) {
            currentSubfolder.bookmarks.push(bm);
          } else if (currentFolder) {
            currentFolder.bookmarks.push(bm);
          } else {
            store.uncategorized.push(bm);
          }
        }
      }
    }
    return store;
  }
  serialize(store) {
    const parts = [];
    if (store.uncategorized.length > 0) {
      for (const bm of store.uncategorized) {
        parts.push(`- [${bm.name}](${bm.url})`);
      }
    }
    for (const folder of store.folders) {
      if (parts.length > 0)
        parts.push("");
      parts.push(`# ${folder.name}`);
      for (const bm of folder.bookmarks) {
        parts.push(`- [${bm.name}](${bm.url})`);
      }
      for (const sub of folder.subfolders) {
        parts.push("");
        parts.push(`## ${sub.name}`);
        for (const bm of sub.bookmarks) {
          parts.push(`- [${bm.name}](${bm.url})`);
        }
      }
    }
    return parts.join("\n") + "\n";
  }
  getFolderOptions(store) {
    const opts = [];
    for (const folder of store.folders) {
      opts.push({ label: folder.name, value: folder.name, isSubfolder: false });
      for (const sub of folder.subfolders) {
        opts.push({
          label: `  ${sub.name}`,
          value: `${folder.name}${FOLDER_SEP}${sub.name}`,
          isSubfolder: true
        });
      }
    }
    return opts;
  }
  async addBookmark(bookmark, targetFolderName, isNewFolder) {
    bookmark = { name: stripCtrl(bookmark.name), url: bookmark.url.replace(/[\x00-\x1f\x7f]/g, "").trim() };
    targetFolderName = stripCtrl(targetFolderName);
    const f = await this.ensureFile();
    await this.app.vault.process(f, (content) => {
      const store = this.parseContent(content);
      if (isNewFolder) {
        store.folders.push({
          name: targetFolderName,
          bookmarks: [bookmark],
          subfolders: []
        });
      } else if (!targetFolderName) {
        store.uncategorized.push(bookmark);
      } else {
        let added = false;
        const sepIdx = targetFolderName.indexOf(FOLDER_SEP);
        if (sepIdx !== -1) {
          const parentName = targetFolderName.slice(0, sepIdx);
          const subName = targetFolderName.slice(sepIdx + 1);
          for (const folder of store.folders) {
            if (folder.name === parentName) {
              const sub = folder.subfolders.find(
                (s) => s.name === subName
              );
              if (sub) {
                sub.bookmarks.push(bookmark);
                added = true;
              }
              break;
            }
          }
        } else {
          for (const folder of store.folders) {
            if (folder.name === targetFolderName) {
              folder.bookmarks.push(bookmark);
              added = true;
              break;
            }
          }
        }
        if (!added) {
          store.folders.push({
            name: targetFolderName,
            bookmarks: [bookmark],
            subfolders: []
          });
        }
      }
      return this.serialize(store);
    });
  }
};

// BookmarkView.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_BOOKMARK = "launchpad-view";
var BookmarkView = class extends import_obsidian2.ItemView {
  constructor(leaf, host) {
    super(leaf);
    this.store = { folders: [], uncategorized: [] };
    this.host = host;
  }
  getViewType() {
    return VIEW_TYPE_BOOKMARK;
  }
  getDisplayText() {
    return "Launchpad";
  }
  getIcon() {
    return "bookmark";
  }
  async onOpen() {
    this.render();
  }
  setStore(store) {
    this.store = store;
    this.render();
  }
  setLoading(isLoading) {
    if (isLoading) {
      this.contentEl.empty();
      this.contentEl.createDiv({ cls: "launchpad-loading", text: "Loading\u2026" });
    }
  }
  render() {
    this.contentEl.empty();
    this.contentEl.addClass("launchpad-content-el");
    const container = this.contentEl.createDiv("launchpad-container");
    container.setAttribute("role", "navigation");
    container.setAttribute("aria-label", "Launchpad");
    const header = container.createDiv("launchpad-header");
    header.createSpan({ text: "Bookmarks" });
    const addBtn = header.createEl("button", {
      cls: "launchpad-add-btn",
      text: "+",
      attr: { "aria-label": "Add bookmark" }
    });
    addBtn.addEventListener("click", () => this.host.openCaptureModal());
    const scrollEl = container.createDiv("launchpad-scroll");
    const collapseState = this.host.getCollapseState();
    if (this.store.uncategorized.length > 0) {
      const section = scrollEl.createDiv("launchpad-uncategorized");
      for (const bm of this.store.uncategorized) {
        this.renderBookmarkItem(section, bm.name, bm.url);
      }
    }
    for (const folder of this.store.folders) {
      this.renderFolder(scrollEl, folder, collapseState, null);
    }
    if (this.store.folders.length === 0 && this.store.uncategorized.length === 0) {
      scrollEl.createDiv({
        cls: "launchpad-empty",
        text: "No bookmarks yet. Press + to add one, or edit your bookmarks file directly."
      });
    }
    const previousFilename = this.host.getPreviousFilename();
    if (previousFilename !== null) {
      const backSection = container.createDiv("launchpad-back-section");
      const backLink = backSection.createEl("a", {
        cls: "launchpad-back-item",
        attr: { href: "#", title: `Go back to ${previousFilename}` }
      });
      const backIconEl = backLink.createSpan({ cls: "lp-item-icon", attr: { "aria-hidden": "true" } });
      (0, import_obsidian2.setIcon)(backIconEl, "arrow-left");
      backLink.createSpan({ cls: "lp-item-name", text: previousFilename });
      backLink.addEventListener("click", (e) => {
        e.preventDefault();
        this.host.navigateBack();
      });
    }
  }
  renderFolder(parent, folder, collapseState, parentName) {
    var _a;
    const key = parentName ? `${parentName}${FOLDER_SEP}${folder.name}` : folder.name;
    const isCollapsed = (_a = collapseState[key]) != null ? _a : false;
    const folderEl = parent.createDiv(
      parentName ? "launchpad-subfolder" : "launchpad-folder"
    );
    const headerCls = parentName ? "launchpad-subfolder-header" : "launchpad-folder-header";
    const headerEl = folderEl.createEl("button", {
      cls: headerCls,
      attr: {
        type: "button",
        "aria-expanded": (!isCollapsed).toString()
      }
    });
    const folderIconEl = headerEl.createSpan({ cls: "lp-folder-icon", attr: { "aria-hidden": "true" } });
    (0, import_obsidian2.setIcon)(folderIconEl, "layers");
    headerEl.createSpan({ text: folder.name });
    const arrow = headerEl.createSpan({
      cls: "launchpad-folder-arrow" + (isCollapsed ? " collapsed" : ""),
      text: "\u25BE",
      attr: { "aria-hidden": "true" }
    });
    const contentEl = folderEl.createDiv(
      parentName ? "launchpad-subfolder-content" : "launchpad-folder-content"
    );
    if (isCollapsed)
      contentEl.addClass("is-collapsed");
    const innerEl = contentEl.createDiv("lp-inner");
    headerEl.addEventListener("click", async () => {
      const nowCollapsed = !contentEl.hasClass("is-collapsed");
      contentEl.toggleClass("is-collapsed", nowCollapsed);
      arrow.classList.toggle("collapsed", nowCollapsed);
      headerEl.setAttribute("aria-expanded", (!nowCollapsed).toString());
      await this.host.setCollapseState(key, nowCollapsed);
    });
    for (const bm of folder.bookmarks) {
      this.renderBookmarkItem(innerEl, bm.name, bm.url);
    }
    for (const sub of folder.subfolders) {
      this.renderFolder(innerEl, sub, collapseState, folder.name);
    }
  }
  renderBookmarkItem(parent, name, url) {
    const item = parent.createEl("a", {
      cls: "launchpad-item",
      attr: { href: "#", title: url }
    });
    const isVault = url.startsWith("vault://");
    const isNote = url.startsWith("note://");
    const itemIconEl = item.createSpan({
      cls: isNote ? "lp-item-icon lp-item-icon--note" : isVault ? "lp-item-icon lp-item-icon--vault" : "lp-item-icon",
      attr: { "aria-hidden": "true" }
    });
    (0, import_obsidian2.setIcon)(itemIconEl, isNote ? "file-text" : isVault ? "library" : "globe");
    item.createSpan({ cls: "lp-item-name", text: name });
    item.addEventListener("click", (e) => {
      e.preventDefault();
      this.host.openBookmarkUrl(url);
    });
  }
};

// CaptureModal.ts
var import_obsidian3 = require("obsidian");
var NEW_FOLDER_VALUE = "__new__";
var UNCATEGORIZED_VALUE = "__uncategorized__";
var URL_PREFIXES = ["https://", "http://", "obsidian://", "vault://", "note://"];
function isWikiLink(val) {
  return val.startsWith("[[") && val.endsWith("]]") && val.length > 4;
}
function normalizeUrl(val) {
  if (isWikiLink(val))
    return "note://" + val.slice(2, -2).trim();
  return val;
}
var CaptureModal = class extends import_obsidian3.Modal {
  constructor(app, store, getFolderOptions) {
    super(app);
    this.store = store;
    this.getFolderOptions = getFolderOptions;
  }
  onOpen() {
    const { contentEl } = this;
    const folderOptions = this.getFolderOptions();
    contentEl.addClass("launchpad-capture-modal");
    new import_obsidian3.Setting(contentEl).setName("Add bookmark").setHeading();
    let nameValue = "";
    let urlValue = "";
    let folderValue = folderOptions.length > 0 ? folderOptions[0].value : UNCATEGORIZED_VALUE;
    let newFolderValue = "";
    const nameField = contentEl.createDiv("launchpad-capture-field");
    const nameLbl = nameField.createEl("label", { text: "Display name" });
    nameLbl.setAttribute("for", "lp-cm-name");
    const nameInput = nameField.createEl("input", {
      attr: {
        id: "lp-cm-name",
        type: "text",
        placeholder: "e.g. Linear Board",
        "aria-describedby": "lp-cm-name-err"
      }
    });
    const nameErrorEl = nameField.createDiv({
      cls: "launchpad-capture-error",
      text: "",
      attr: { id: "lp-cm-name-err", "aria-live": "polite" }
    });
    const urlField = contentEl.createDiv("launchpad-capture-field");
    const urlLbl = urlField.createEl("label", { text: "URL" });
    urlLbl.setAttribute("for", "lp-cm-url");
    const urlInput = urlField.createEl("input", {
      attr: {
        id: "lp-cm-url",
        type: "text",
        placeholder: "https://, obsidian://, vault://, note://, or [[note name]]",
        "aria-describedby": "lp-cm-url-err"
      }
    });
    const urlErrorEl = urlField.createDiv({
      cls: "launchpad-capture-error",
      text: "",
      attr: { id: "lp-cm-url-err", "aria-live": "polite" }
    });
    const folderField = contentEl.createDiv("launchpad-capture-field");
    const folderLbl = folderField.createEl("label", { text: "Target folder" });
    folderLbl.setAttribute("for", "lp-cm-folder");
    const folderSelect = folderField.createEl("select", {
      attr: { id: "lp-cm-folder" }
    });
    if (folderOptions.length === 0) {
      const opt = folderSelect.createEl("option", {
        text: "Uncategorized",
        attr: { value: UNCATEGORIZED_VALUE }
      });
      opt.selected = true;
    } else {
      for (const opt of folderOptions) {
        folderSelect.createEl("option", {
          text: opt.label,
          attr: { value: opt.value }
        });
      }
    }
    folderSelect.createEl("option", {
      text: "+ New folder\u2026",
      attr: { value: NEW_FOLDER_VALUE }
    });
    const newFolderField = contentEl.createDiv("launchpad-capture-field launchpad-hidden");
    const newFolderLbl = newFolderField.createEl("label", { text: "New folder name" });
    newFolderLbl.setAttribute("for", "lp-cm-new-folder");
    const newFolderInput = newFolderField.createEl("input", {
      attr: { id: "lp-cm-new-folder", type: "text", placeholder: "Folder name" }
    });
    folderSelect.addEventListener("change", () => {
      folderValue = folderSelect.value;
      newFolderField.toggleClass("launchpad-hidden", folderValue !== NEW_FOLDER_VALUE);
      updateSaveBtn();
    });
    newFolderInput.addEventListener("input", () => {
      newFolderValue = newFolderInput.value.trim();
      updateSaveBtn();
    });
    const actions = contentEl.createDiv("launchpad-capture-actions");
    const cancelBtn = actions.createEl("button", { text: "Cancel" });
    const saveBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: "Save"
    });
    const saveErrorEl = contentEl.createDiv({
      cls: "launchpad-capture-error",
      text: "",
      attr: { "aria-live": "polite" }
    });
    const updateSaveBtn = () => {
      const nameOk = nameValue.trim().length > 0;
      const urlOk = URL_PREFIXES.some((p) => urlValue.trim().startsWith(p)) || isWikiLink(urlValue.trim());
      const folderOk = folderValue !== NEW_FOLDER_VALUE || newFolderValue.trim().length > 0;
      saveBtn.disabled = !(nameOk && urlOk && folderOk);
    };
    nameInput.addEventListener("input", () => {
      nameValue = nameInput.value;
      nameErrorEl.textContent = nameValue.trim().length === 0 ? "Name is required." : "";
      updateSaveBtn();
    });
    urlInput.addEventListener("input", () => {
      urlValue = urlInput.value;
      const valid = URL_PREFIXES.some((p) => urlValue.trim().startsWith(p)) || isWikiLink(urlValue.trim());
      urlErrorEl.textContent = valid ? "" : "URL must start with https://, http://, obsidian://, vault://, note://, or be [[note name]]";
      updateSaveBtn();
    });
    cancelBtn.addEventListener("click", () => this.close());
    saveBtn.addEventListener("click", async () => {
      if (saveBtn.disabled)
        return;
      saveBtn.disabled = true;
      saveErrorEl.textContent = "";
      const name = nameValue.trim();
      const url = normalizeUrl(urlValue.trim());
      const isNew = folderValue === NEW_FOLDER_VALUE;
      const targetFolder = isNew ? newFolderValue.trim() : folderValue === UNCATEGORIZED_VALUE ? "" : folderValue;
      if (!name || !URL_PREFIXES.some((p) => url.startsWith(p))) {
        saveBtn.disabled = false;
        return;
      }
      if (isNew && !targetFolder) {
        saveBtn.disabled = false;
        return;
      }
      try {
        const bm = { name, url };
        await this.store.addBookmark(bm, targetFolder, isNew);
        this.close();
      } catch (err) {
        saveBtn.disabled = false;
        console.error("Launchpad: failed to save bookmark", err);
        saveErrorEl.textContent = "Failed to save. Please try again.";
      }
    });
    updateSaveBtn();
    const handleKeydown = (e) => {
      if (e.key === "Enter" && !saveBtn.disabled) {
        saveBtn.click();
      }
    };
    nameInput.addEventListener("keydown", handleKeydown);
    urlInput.addEventListener("keydown", handleKeydown);
    newFolderInput.addEventListener("keydown", handleKeydown);
    nameInput.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// SetupModal.ts
var import_obsidian4 = require("obsidian");
var SetupModal = class extends import_obsidian4.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("launchpad-setup-modal");
    new import_obsidian4.Setting(contentEl).setName("Set up Launchpad").setHeading();
    contentEl.createEl("p", {
      cls: "launchpad-setup-description",
      text: "Choose where to store your bookmarks file. You can place it anywhere inside your vault \u2014 it stays a plain Markdown file you can edit directly."
    });
    let pathValue = "bookmarks.md";
    const pathField = contentEl.createDiv("launchpad-capture-field");
    const pathLbl = pathField.createEl("label", { text: "File path (relative to vault root)" });
    pathLbl.setAttribute("for", "lp-sm-path");
    const pathInput = pathField.createEl("input", {
      attr: {
        id: "lp-sm-path",
        type: "text",
        placeholder: "bookmarks.md  or  Resources/bookmarks.md",
        "aria-describedby": "lp-sm-path-err"
      }
    });
    pathInput.value = pathValue;
    const errorEl = pathField.createDiv({
      cls: "launchpad-capture-error",
      text: "",
      attr: { id: "lp-sm-path-err", "aria-live": "polite" }
    });
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian4.TFolder && f.path !== "/").sort((a, b) => a.path.localeCompare(b.path)).slice(0, 8);
    if (folders.length > 0) {
      const hintRow = pathField.createDiv("launchpad-setup-hint");
      hintRow.createSpan({ cls: "launchpad-setup-hint-label", text: "Folders: " });
      for (const folder of folders) {
        const chip = hintRow.createEl("button", {
          cls: "launchpad-setup-chip",
          text: folder.path,
          attr: { type: "button" }
        });
        chip.addEventListener("click", () => {
          const filename = pathInput.value.trim().split("/").pop() || "bookmarks.md";
          pathInput.value = `${folder.path}/${filename}`;
          pathValue = pathInput.value;
          errorEl.textContent = validate(pathValue);
          confirmBtn.disabled = !!validate(pathValue);
          pathInput.focus();
        });
      }
    }
    const validate = (val) => {
      const v = val.trim();
      if (!v)
        return "Path is required.";
      if (!v.endsWith(".md"))
        return "File must end with .md";
      if (v.startsWith("/"))
        return "Use a relative path \u2014 no leading slash.";
      if (v.includes(".."))
        return "Path cannot contain ..";
      if (/[\x00-\x1f\x7f]/.test(v))
        return "Path contains invalid characters.";
      return "";
    };
    pathInput.addEventListener("input", () => {
      pathValue = pathInput.value;
      errorEl.textContent = validate(pathValue);
      confirmBtn.disabled = !!validate(pathValue);
    });
    const actions = contentEl.createDiv("launchpad-capture-actions");
    const cancelBtn = actions.createEl("button", { text: "Later" });
    cancelBtn.addEventListener("click", () => this.close());
    const confirmBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: "Create file"
    });
    confirmBtn.addEventListener("click", async () => {
      const err = validate(pathValue.trim());
      if (err) {
        errorEl.textContent = err;
        return;
      }
      confirmBtn.disabled = true;
      confirmBtn.setText("Creating\u2026");
      await this.onConfirm((0, import_obsidian4.normalizePath)(pathValue.trim()));
      this.close();
    });
    pathInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !confirmBtn.disabled)
        confirmBtn.click();
    });
    pathInput.focus();
    pathInput.select();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// main.ts
var DEFAULT_DATA = {
  collapseState: {},
  bookmarksFilePath: null
};
var LaunchpadPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    /** File that was active immediately before an obsidian:// bookmark click. */
    this.previousFile = null;
    /** Pending exponential-backoff retry for refreshViews when iCloud read fails. */
    this.refreshRetryTimer = null;
  }
  async onload() {
    var _a;
    this.data = Object.assign({}, DEFAULT_DATA, await this.loadData());
    this.store = new BookmarkStoreManager(
      this.app,
      (_a = this.data.bookmarksFilePath) != null ? _a : DEFAULT_BOOKMARKS_FILE
    );
    this.registerView(VIEW_TYPE_BOOKMARK, (leaf) => new BookmarkView(leaf, this));
    this.addRibbonIcon("bookmark", "Launchpad", () => this.revealPanel());
    this.addCommand({
      id: "add-bookmark",
      name: "Add bookmark",
      callback: () => this.openCaptureModal()
    });
    this.addCommand({
      id: "open-panel",
      name: "Open panel",
      callback: () => this.revealPanel()
    });
    this.addCommand({
      id: "configure-file",
      name: "Configure bookmarks file location",
      callback: () => this.showSetupModal()
    });
    const onBookmarksFileModify = (file) => {
      if (file instanceof import_obsidian5.TFile && file.path === this.store.getFilePath())
        this.refreshViews();
    };
    this.registerEvent(this.app.vault.on("modify", onBookmarksFileModify));
    const onBookmarksFileCreate = (file) => {
      if (file instanceof import_obsidian5.TFile && file.path === this.store.getFilePath())
        this.refreshViews();
    };
    this.registerEvent(this.app.vault.on("create", onBookmarksFileCreate));
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        const path = this.store.getFilePath();
        if (file instanceof import_obsidian5.TFile && (file.path === path || oldPath === path)) {
          this.refreshViews();
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian5.TFolder))
          return;
        const launchpadPath = "vault://" + file.path.split("/").map(encodeURIComponent).join("/");
        menu.addItem(
          (item) => item.setTitle("Copy path for Launchpad").setIcon("copy").setSection("info").onClick(() => navigator.clipboard.writeText(launchpadPath))
        );
      })
    );
    this.app.workspace.onLayoutReady(() => this.initOnReady());
  }
  async onunload() {
    if (this.refreshRetryTimer !== null) {
      window.clearTimeout(this.refreshRetryTimer);
      this.refreshRetryTimer = null;
    }
  }
  // ── Startup ────────────────────────────────────────────────────────────
  async initOnReady() {
    if (this.data.bookmarksFilePath) {
      await this.openAndRefresh();
      return;
    }
    const legacyFile = this.app.vault.getAbstractFileByPath(DEFAULT_BOOKMARKS_FILE);
    if (legacyFile instanceof import_obsidian5.TFile) {
      await this.adoptPath(DEFAULT_BOOKMARKS_FILE);
      await this.openAndRefresh();
      return;
    }
    this.showSetupModal();
  }
  /** Ensures the sidebar panel is open and populated. */
  async openAndRefresh() {
    await this.ensurePanelOpen();
    await this.refreshViews();
  }
  /** Adds the panel to the right sidebar if it is not already there. */
  async ensurePanelOpen() {
    var _a;
    if (this.app.workspace.getLeavesOfType(VIEW_TYPE_BOOKMARK).length > 0) {
      return;
    }
    const leaf = (_a = this.app.workspace.getRightLeaf(false)) != null ? _a : this.app.workspace.getRightLeaf(true);
    if (!leaf)
      return;
    await leaf.setViewState({ type: VIEW_TYPE_BOOKMARK, active: true });
  }
  // ── Setup modal ────────────────────────────────────────────────────────
  showSetupModal() {
    new SetupModal(this.app, async (chosenPath) => {
      await this.adoptPath(chosenPath);
      await this.store.ensureFile();
      await this.revealPanel();
    }).open();
  }
  /** Persist a confirmed bookmarks file path and point the store at it. */
  async adoptPath(path) {
    this.data.bookmarksFilePath = path;
    await this.saveData(this.data);
    this.store.setFilePath(path);
  }
  // ── BookmarkViewHost ───────────────────────────────────────────────────
  async openCaptureModal() {
    const storeData = await this.store.parse();
    new CaptureModal(
      this.app,
      this.store,
      () => this.store.getFolderOptions(storeData)
    ).open();
  }
  getCollapseState() {
    return this.data.collapseState;
  }
  async setCollapseState(key, collapsed) {
    this.data.collapseState[key] = collapsed;
    await this.saveData(this.data);
  }
  openBookmarkUrl(url) {
    if (/[\x00-\x1f\x7f]/.test(url)) {
      new import_obsidian5.Notice("Launchpad: URL contains invalid characters and was not opened.");
      return;
    }
    if (url.startsWith("vault://")) {
      const folderPath = decodeURIComponent(url.slice("vault://".length));
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (!(folder instanceof import_obsidian5.TFolder)) {
        new import_obsidian5.Notice(`Launchpad: folder not found \u2014 ${folderPath}`);
        return;
      }
      const leaves = this.app.workspace.getLeavesOfType("file-explorer");
      if (leaves.length > 0) {
        try {
          this.app.workspace.revealLeaf(leaves[0]);
          const view = leaves[0].view;
          if (typeof view.revealInFolder === "function") {
            view.revealInFolder(folder);
            return;
          }
        } catch (e) {
        }
      }
      new import_obsidian5.Notice(`Launchpad: ${folderPath}`);
    } else if (url.startsWith("note://")) {
      const notePath = url.slice("note://".length);
      const file = this.app.metadataCache.getFirstLinkpathDest(notePath, "");
      if (!file) {
        new import_obsidian5.Notice(`Launchpad: note not found \u2014 ${notePath}`);
        return;
      }
      this.app.workspace.getLeaf(false).openFile(file);
    } else if (url.startsWith("obsidian://")) {
      this.previousFile = this.app.workspace.getActiveFile();
      window.open(url);
      this.refreshViews();
    } else if (url.startsWith("https://") || url.startsWith("http://")) {
      window.open(url, "_blank", "noopener,noreferrer");
    }
  }
  getPreviousFilename() {
    var _a, _b;
    return (_b = (_a = this.previousFile) == null ? void 0 : _a.basename) != null ? _b : null;
  }
  async navigateBack() {
    const file = this.previousFile;
    if (!file)
      return;
    this.previousFile = null;
    if (!(this.app.vault.getAbstractFileByPath(file.path) instanceof import_obsidian5.TFile)) {
      await this.refreshViews();
      return;
    }
    await this.app.workspace.getLeaf(false).openFile(file);
    await this.refreshViews();
  }
  // ── Panel management ───────────────────────────────────────────────────
  async revealPanel() {
    var _a;
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_BOOKMARK);
    if (existing.length > 0) {
      const leaf = existing[0];
      this.app.workspace.setActiveLeaf(leaf, { focus: true });
      this.app.workspace.revealLeaf(leaf);
    } else {
      const leaf = (_a = this.app.workspace.getRightLeaf(false)) != null ? _a : this.app.workspace.getRightLeaf(true);
      if (!leaf)
        return;
      await leaf.setViewState({ type: VIEW_TYPE_BOOKMARK, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
    await this.refreshViews();
  }
  async refreshViews(retryCount = 0) {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_BOOKMARK);
    if (leaves.length === 0)
      return;
    for (const leaf of leaves) {
      if (leaf.view instanceof BookmarkView) {
        leaf.view.setLoading(true);
      }
    }
    let storeData;
    try {
      storeData = await this.store.parse();
    } catch (e) {
      if (retryCount < 6) {
        this.refreshRetryTimer = window.setTimeout(
          () => this.refreshViews(retryCount + 1),
          1e3 * Math.pow(2, retryCount)
        );
      }
      return;
    }
    if (this.refreshRetryTimer !== null) {
      window.clearTimeout(this.refreshRetryTimer);
      this.refreshRetryTimer = null;
    }
    for (const leaf of leaves) {
      if (leaf.view instanceof BookmarkView) {
        leaf.view.setStore(storeData);
      }
    }
  }
};
