/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BookmarkLauncherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// BookmarkStore.ts
var import_obsidian = require("obsidian");
var DEFAULT_BOOKMARKS_FILE = "bookmarks.md";
var BOOKMARK_RE = /^\s*-\s+\[([^\]]+)\]\(([^)]+)\)\s*$/;
var ALLOWED_SCHEMES = ["https://", "http://", "obsidian://"];
var BookmarkStoreManager = class {
  constructor(app, filePath = DEFAULT_BOOKMARKS_FILE) {
    this.writing = false;
    this.app = app;
    this.filePath = filePath;
  }
  getFilePath() {
    return this.filePath;
  }
  setFilePath(path) {
    this.filePath = path;
  }
  getFile() {
    const f = this.app.vault.getAbstractFileByPath(this.filePath);
    return f instanceof import_obsidian.TFile ? f : null;
  }
  /** Creates any missing parent folders for this.filePath. */
  async ensureParentFolders() {
    const segments = this.filePath.split("/");
    segments.pop();
    if (segments.length === 0)
      return;
    let current = "";
    for (const seg of segments) {
      current = current ? `${current}/${seg}` : seg;
      const node = this.app.vault.getAbstractFileByPath(current);
      if (!node) {
        try {
          await this.app.vault.createFolder(current);
        } catch (e) {
        }
      }
    }
  }
  async ensureFile() {
    let f = this.getFile();
    if (!f) {
      await this.ensureParentFolders();
      await this.app.vault.create(this.filePath, "");
      f = this.getFile();
    }
    return f;
  }
  async parse() {
    const f = this.getFile();
    if (!f)
      return { folders: [], uncategorized: [] };
    const content = await this.app.vault.read(f);
    return this.parseContent(content);
  }
  parseContent(content) {
    const lines = content.split("\n");
    const store = { folders: [], uncategorized: [] };
    let currentFolder = null;
    let currentSubfolder = null;
    for (const line of lines) {
      if (line.startsWith("## ")) {
        const name = line.slice(3).trim();
        if (currentFolder) {
          currentSubfolder = { name, bookmarks: [], subfolders: [] };
          currentFolder.subfolders.push(currentSubfolder);
        }
      } else if (line.startsWith("# ")) {
        const name = line.slice(2).trim();
        currentSubfolder = null;
        currentFolder = { name, bookmarks: [], subfolders: [] };
        store.folders.push(currentFolder);
      } else {
        const m = line.match(BOOKMARK_RE);
        if (m) {
          const parsedUrl = m[2];
          if (!ALLOWED_SCHEMES.some((s) => parsedUrl.startsWith(s))) {
            continue;
          }
          const bm = { name: m[1], url: parsedUrl };
          if (currentSubfolder) {
            currentSubfolder.bookmarks.push(bm);
          } else if (currentFolder) {
            currentFolder.bookmarks.push(bm);
          } else {
            store.uncategorized.push(bm);
          }
        }
      }
    }
    return store;
  }
  serialize(store) {
    const parts = [];
    if (store.uncategorized.length > 0) {
      for (const bm of store.uncategorized) {
        parts.push(`- [${bm.name}](${bm.url})`);
      }
    }
    for (const folder of store.folders) {
      if (parts.length > 0)
        parts.push("");
      parts.push(`# ${folder.name}`);
      for (const bm of folder.bookmarks) {
        parts.push(`- [${bm.name}](${bm.url})`);
      }
      for (const sub of folder.subfolders) {
        parts.push("");
        parts.push(`## ${sub.name}`);
        for (const bm of sub.bookmarks) {
          parts.push(`- [${bm.name}](${bm.url})`);
        }
      }
    }
    return parts.join("\n");
  }
  getFolderOptions(store) {
    const opts = [];
    for (const folder of store.folders) {
      opts.push({ label: folder.name, value: folder.name, isSubfolder: false });
      for (const sub of folder.subfolders) {
        opts.push({
          label: `  ${sub.name}`,
          value: sub.name,
          isSubfolder: true
        });
      }
    }
    return opts;
  }
  async addBookmark(bookmark, targetFolderName, isNewFolder) {
    if (this.writing)
      return;
    this.writing = true;
    try {
      const f = await this.ensureFile();
      const content = await this.app.vault.read(f);
      const store = this.parseContent(content);
      if (isNewFolder) {
        store.folders.push({
          name: targetFolderName,
          bookmarks: [bookmark],
          subfolders: []
        });
      } else if (!targetFolderName) {
        store.uncategorized.push(bookmark);
      } else {
        let added = false;
        for (const folder of store.folders) {
          if (folder.name === targetFolderName) {
            folder.bookmarks.push(bookmark);
            added = true;
            break;
          }
          for (const sub of folder.subfolders) {
            if (sub.name === targetFolderName) {
              sub.bookmarks.push(bookmark);
              added = true;
              break;
            }
          }
          if (added)
            break;
        }
        if (!added) {
          store.folders.push({
            name: targetFolderName,
            bookmarks: [bookmark],
            subfolders: []
          });
        }
      }
      await this.app.vault.modify(f, this.serialize(store));
    } finally {
      this.writing = false;
    }
  }
};

// BookmarkView.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_BOOKMARK = "bookmark-launcher-view";
var BookmarkView = class extends import_obsidian2.ItemView {
  constructor(leaf, host) {
    super(leaf);
    this.store = { folders: [], uncategorized: [] };
    this.host = host;
  }
  getViewType() {
    return VIEW_TYPE_BOOKMARK;
  }
  getDisplayText() {
    return "Bookmark Launcher";
  }
  getIcon() {
    return "bookmark";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  setStore(store) {
    this.store = store;
    this.render();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("bookmark-launcher-container");
    const header = container.createDiv("bookmark-launcher-header");
    header.createSpan({ text: "Bookmarks" });
    const addBtn = header.createEl("button", {
      cls: "bookmark-launcher-add-btn",
      text: "+",
      attr: { "aria-label": "Add bookmark" }
    });
    addBtn.addEventListener("click", () => this.host.openCaptureModal());
    const collapseState = this.host.getCollapseState();
    if (this.store.uncategorized.length > 0) {
      const section = container.createDiv("bookmark-launcher-uncategorized");
      for (const bm of this.store.uncategorized) {
        this.renderBookmarkItem(section, bm.name, bm.url);
      }
    }
    for (const folder of this.store.folders) {
      this.renderFolder(container, folder, collapseState, null);
    }
    if (this.store.folders.length === 0 && this.store.uncategorized.length === 0) {
      container.createDiv({
        cls: "bookmark-launcher-empty",
        text: "No bookmarks yet. Press + to add one, or edit bookmarks.md directly."
      });
    }
  }
  renderFolder(parent, folder, collapseState, parentName) {
    var _a;
    const key = parentName ? `${parentName}/${folder.name}` : folder.name;
    const isCollapsed = (_a = collapseState[key]) != null ? _a : false;
    const folderEl = parent.createDiv(
      parentName ? "bookmark-launcher-subfolder" : "bookmark-launcher-folder"
    );
    const headerCls = parentName ? "bookmark-launcher-subfolder-header" : "bookmark-launcher-folder-header";
    const headerEl = folderEl.createDiv(headerCls);
    const arrow = headerEl.createSpan({
      cls: "bookmark-launcher-folder-arrow" + (isCollapsed ? " collapsed" : ""),
      text: "\u25BE"
    });
    headerEl.createSpan({ text: folder.name });
    const contentEl = folderEl.createDiv(
      parentName ? "bookmark-launcher-subfolder-content" : "bookmark-launcher-folder-content"
    );
    if (isCollapsed)
      contentEl.addClass("is-collapsed");
    const innerEl = contentEl.createDiv("bl-inner");
    headerEl.addEventListener("click", async () => {
      const nowCollapsed = !contentEl.hasClass("is-collapsed");
      contentEl.toggleClass("is-collapsed", nowCollapsed);
      arrow.classList.toggle("collapsed", nowCollapsed);
      await this.host.setCollapseState(key, nowCollapsed);
    });
    for (const bm of folder.bookmarks) {
      this.renderBookmarkItem(innerEl, bm.name, bm.url);
    }
    for (const sub of folder.subfolders) {
      this.renderFolder(innerEl, sub, collapseState, folder.name);
    }
  }
  renderBookmarkItem(parent, name, url) {
    const item = parent.createEl("a", {
      cls: "bookmark-launcher-item",
      text: name,
      attr: { href: "#", title: url }
    });
    item.addEventListener("click", (e) => {
      e.preventDefault();
      if (url.startsWith("obsidian://")) {
        window.open(url);
      } else if (url.startsWith("https://") || url.startsWith("http://")) {
        window.open(url, "_blank", "noopener,noreferrer");
      }
    });
  }
};

// CaptureModal.ts
var import_obsidian3 = require("obsidian");
var NEW_FOLDER_VALUE = "__new__";
var UNCATEGORIZED_VALUE = "__uncategorized__";
var URL_PREFIXES = ["https://", "http://", "obsidian://"];
var CaptureModal = class extends import_obsidian3.Modal {
  constructor(app, store, folderOptions) {
    super(app);
    this.store = store;
    this.folderOptions = folderOptions;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("bookmark-capture-modal");
    contentEl.createEl("h2", { text: "Add Bookmark" });
    let nameValue = "";
    let urlValue = "";
    let folderValue = this.folderOptions.length > 0 ? this.folderOptions[0].value : UNCATEGORIZED_VALUE;
    let newFolderValue = "";
    let urlError = "";
    let nameError = "";
    const nameField = contentEl.createDiv("bookmark-capture-field");
    nameField.createEl("label", { text: "Display Name" });
    const nameInput = nameField.createEl("input", {
      attr: { type: "text", placeholder: "e.g. Linear Board" }
    });
    const nameErrorEl = nameField.createDiv({
      cls: "bookmark-capture-error",
      text: ""
    });
    nameInput.style.width = "100%";
    const urlField = contentEl.createDiv("bookmark-capture-field");
    urlField.createEl("label", { text: "URL" });
    const urlInput = urlField.createEl("input", {
      attr: {
        type: "text",
        placeholder: "https:// or obsidian://"
      }
    });
    const urlErrorEl = urlField.createDiv({
      cls: "bookmark-capture-error",
      text: ""
    });
    urlInput.style.width = "100%";
    const folderField = contentEl.createDiv("bookmark-capture-field");
    folderField.createEl("label", { text: "Target Folder" });
    const folderSelect = folderField.createEl("select");
    folderSelect.style.width = "100%";
    if (this.folderOptions.length === 0) {
      const opt = folderSelect.createEl("option", {
        text: "Uncategorized",
        attr: { value: UNCATEGORIZED_VALUE }
      });
      opt.selected = true;
    } else {
      for (const opt of this.folderOptions) {
        folderSelect.createEl("option", {
          text: opt.label,
          attr: { value: opt.value }
        });
      }
    }
    folderSelect.createEl("option", {
      text: "+ New folder\u2026",
      attr: { value: NEW_FOLDER_VALUE }
    });
    const newFolderField = contentEl.createDiv("bookmark-capture-field");
    newFolderField.style.display = "none";
    newFolderField.createEl("label", { text: "New Folder Name" });
    const newFolderInput = newFolderField.createEl("input", {
      attr: { type: "text", placeholder: "Folder name" }
    });
    newFolderInput.style.width = "100%";
    folderSelect.addEventListener("change", () => {
      folderValue = folderSelect.value;
      newFolderField.style.display = folderValue === NEW_FOLDER_VALUE ? "" : "none";
      updateSaveBtn();
    });
    newFolderInput.addEventListener("input", () => {
      newFolderValue = newFolderInput.value.trim();
      updateSaveBtn();
    });
    const actions = contentEl.createDiv("bookmark-capture-actions");
    const cancelBtn = actions.createEl("button", { text: "Cancel" });
    const saveBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: "Save"
    });
    const updateSaveBtn = () => {
      const nameOk = nameValue.trim().length > 0;
      const urlOk = URL_PREFIXES.some((p) => urlValue.trim().startsWith(p));
      const folderOk = folderValue !== NEW_FOLDER_VALUE || newFolderValue.trim().length > 0;
      saveBtn.disabled = !(nameOk && urlOk && folderOk);
    };
    nameInput.addEventListener("input", () => {
      nameValue = nameInput.value;
      nameErrorEl.textContent = nameValue.trim().length === 0 ? "Name is required." : "";
      updateSaveBtn();
    });
    urlInput.addEventListener("input", () => {
      urlValue = urlInput.value;
      const valid = URL_PREFIXES.some((p) => urlValue.trim().startsWith(p));
      urlErrorEl.textContent = valid ? "" : "URL must start with https://, http://, or obsidian://";
      updateSaveBtn();
    });
    cancelBtn.addEventListener("click", () => this.close());
    saveBtn.addEventListener("click", async () => {
      const name = nameValue.trim();
      const url = urlValue.trim();
      const isNew = folderValue === NEW_FOLDER_VALUE;
      const targetFolder = isNew ? newFolderValue.trim() : folderValue === UNCATEGORIZED_VALUE ? "" : folderValue;
      if (!name || !URL_PREFIXES.some((p) => url.startsWith(p)))
        return;
      if (isNew && !targetFolder)
        return;
      const bm = { name, url };
      await this.store.addBookmark(bm, targetFolder, isNew);
      this.close();
    });
    updateSaveBtn();
    const handleKeydown = (e) => {
      if (e.key === "Enter" && !saveBtn.disabled) {
        saveBtn.click();
      }
    };
    nameInput.addEventListener("keydown", handleKeydown);
    urlInput.addEventListener("keydown", handleKeydown);
    newFolderInput.addEventListener("keydown", handleKeydown);
    nameInput.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// SetupModal.ts
var import_obsidian4 = require("obsidian");
var SetupModal = class extends import_obsidian4.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("bookmark-setup-modal");
    contentEl.createEl("h2", { text: "Set up Bookmark Launcher" });
    contentEl.createEl("p", {
      cls: "bookmark-setup-description",
      text: "Choose where to store your bookmarks file. You can place it anywhere inside your vault \u2014 it stays a plain Markdown file you can edit directly."
    });
    let pathValue = "bookmarks.md";
    const pathField = contentEl.createDiv("bookmark-capture-field");
    pathField.createEl("label", { text: "File path (relative to vault root)" });
    const pathInput = pathField.createEl("input", {
      attr: {
        type: "text",
        placeholder: "bookmarks.md  or  Resources/bookmarks.md"
      }
    });
    pathInput.value = pathValue;
    pathInput.style.width = "100%";
    const errorEl = pathField.createDiv({ cls: "bookmark-capture-error", text: "" });
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian4.TFolder && f.path !== "/").sort((a, b) => a.path.localeCompare(b.path)).slice(0, 8);
    if (folders.length > 0) {
      const hintRow = pathField.createDiv("bookmark-setup-hint");
      hintRow.createSpan({ cls: "bookmark-setup-hint-label", text: "Folders: " });
      for (const folder of folders) {
        const chip = hintRow.createEl("button", {
          cls: "bookmark-setup-chip",
          text: folder.path,
          attr: { type: "button" }
        });
        chip.addEventListener("click", () => {
          const filename = pathInput.value.trim().split("/").pop() || "bookmarks.md";
          pathInput.value = `${folder.path}/${filename}`;
          pathValue = pathInput.value;
          errorEl.textContent = validate(pathValue);
          confirmBtn.disabled = !!validate(pathValue);
          pathInput.focus();
        });
      }
    }
    const validate = (val) => {
      const v = val.trim();
      if (!v)
        return "Path is required.";
      if (!v.endsWith(".md"))
        return "File must end with .md";
      if (v.startsWith("/"))
        return "Use a relative path \u2014 no leading slash.";
      if (v.includes(".."))
        return "Path cannot contain ..";
      return "";
    };
    pathInput.addEventListener("input", () => {
      pathValue = pathInput.value;
      errorEl.textContent = validate(pathValue);
      confirmBtn.disabled = !!validate(pathValue);
    });
    const actions = contentEl.createDiv("bookmark-capture-actions");
    const cancelBtn = actions.createEl("button", { text: "Later" });
    cancelBtn.addEventListener("click", () => this.close());
    const confirmBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: "Create file"
    });
    confirmBtn.addEventListener("click", async () => {
      const err = validate(pathValue.trim());
      if (err) {
        errorEl.textContent = err;
        return;
      }
      confirmBtn.disabled = true;
      confirmBtn.setText("Creating\u2026");
      await this.onConfirm(pathValue.trim());
      this.close();
    });
    pathInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !confirmBtn.disabled)
        confirmBtn.click();
    });
    pathInput.focus();
    pathInput.select();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// main.ts
var DEFAULT_DATA = {
  collapseState: {},
  bookmarksFilePath: null
};
var BookmarkLauncherPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    var _a;
    this.data = Object.assign({}, DEFAULT_DATA, await this.loadData());
    this.store = new BookmarkStoreManager(
      this.app,
      (_a = this.data.bookmarksFilePath) != null ? _a : DEFAULT_BOOKMARKS_FILE
    );
    this.registerView(VIEW_TYPE_BOOKMARK, (leaf) => new BookmarkView(leaf, this));
    this.addCommand({
      id: "add-bookmark",
      name: "Add bookmark",
      callback: () => this.openCaptureModal()
    });
    this.addCommand({
      id: "open-panel",
      name: "Open panel",
      callback: () => this.revealPanel()
    });
    this.addCommand({
      id: "configure-file",
      name: "Configure bookmarks file location",
      callback: () => this.showSetupModal()
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian5.TFile && file.path === this.store.getFilePath()) {
          this.refreshViews();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian5.TFile && file.path === this.store.getFilePath()) {
          this.refreshViews();
        }
      })
    );
    this.app.workspace.onLayoutReady(() => this.initOnReady());
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_BOOKMARK);
  }
  // ── Startup ────────────────────────────────────────────────────────────
  async initOnReady() {
    if (this.data.bookmarksFilePath) {
      await this.refreshViews();
      return;
    }
    const legacyFile = this.app.vault.getAbstractFileByPath(DEFAULT_BOOKMARKS_FILE);
    if (legacyFile instanceof import_obsidian5.TFile) {
      await this.adoptPath(DEFAULT_BOOKMARKS_FILE);
      await this.refreshViews();
      return;
    }
    this.showSetupModal();
  }
  // ── Setup modal ────────────────────────────────────────────────────────
  showSetupModal() {
    new SetupModal(this.app, async (chosenPath) => {
      await this.adoptPath(chosenPath);
      await this.store.ensureFile();
      await this.refreshViews();
      await this.revealPanel();
    }).open();
  }
  /** Persist a confirmed bookmarks file path and point the store at it. */
  async adoptPath(path) {
    this.data.bookmarksFilePath = path;
    await this.saveData(this.data);
    this.store.setFilePath(path);
  }
  // ── BookmarkViewHost ───────────────────────────────────────────────────
  openCaptureModal() {
    this.store.parse().then((storeData) => {
      const folderOptions = this.store.getFolderOptions(storeData);
      new CaptureModal(this.app, this.store, folderOptions).open();
    });
  }
  getCollapseState() {
    return this.data.collapseState;
  }
  async setCollapseState(key, collapsed) {
    this.data.collapseState[key] = collapsed;
    await this.saveData(this.data);
  }
  // ── Panel management ───────────────────────────────────────────────────
  async revealPanel() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_BOOKMARK);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    await leaf.setViewState({ type: VIEW_TYPE_BOOKMARK, active: true });
    this.app.workspace.revealLeaf(leaf);
    await this.refreshViews();
  }
  async refreshViews() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_BOOKMARK);
    if (leaves.length === 0)
      return;
    const storeData = await this.store.parse();
    for (const leaf of leaves) {
      if (leaf.view instanceof BookmarkView) {
        leaf.view.setStore(storeData);
      }
    }
  }
};
