/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LaunchpadPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// BookmarkStore.ts
var import_obsidian = require("obsidian");
var DEFAULT_BOOKMARKS_FILE = "bookmarks.md";
var BOOKMARK_RE = /^\s*-\s+\[(.+?)\]\((.+)\)\s*$/;
var ALLOWED_SCHEMES = ["https://", "http://", "obsidian://", "vault://", "note://"];
var FOLDER_SEP = "";
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function stripCtrl(s) {
  return s.replace(/[\x00-\x1f\x7f]/g, " ").trim();
}
var BookmarkStoreManager = class {
  constructor(app, filePath = DEFAULT_BOOKMARKS_FILE) {
    this.app = app;
    this.filePath = filePath;
  }
  getFilePath() {
    return this.filePath;
  }
  setFilePath(path) {
    this.filePath = path;
  }
  getFile() {
    if (!this.app.metadataCache)
      return null;
    const f = this.app.vault.getAbstractFileByPath(this.filePath);
    return f instanceof import_obsidian.TFile ? f : null;
  }
  /** Creates any missing parent folders for this.filePath. */
  async ensureParentFolders() {
    const dirs = this.filePath.split("/").slice(0, -1);
    if (dirs.length === 0)
      return;
    let current = "";
    for (const seg of dirs) {
      current = current ? `${current}/${seg}` : seg;
      const node = this.app.vault.getAbstractFileByPath(current);
      if (!node) {
        try {
          await this.app.vault.createFolder(current);
        } catch (e) {
        }
      }
    }
  }
  async ensureFile() {
    let f = this.getFile();
    if (!f) {
      try {
        const stat = await this.app.vault.adapter.stat(this.filePath);
        if (stat && stat.size > 0) {
          await sleep(600);
          f = this.getFile();
        }
      } catch (e) {
      }
    }
    if (!f) {
      await this.ensureParentFolders();
      try {
        await this.app.vault.create(this.filePath, "");
      } catch (e) {
        f = this.getFile();
        if (!f) {
          throw new Error(
            `Bookmark Launcher: "${this.filePath}" already exists on disk but could not be opened. Try re-opening Obsidian.`
          );
        }
        return f;
      }
      f = this.getFile();
      if (!f) {
        throw new Error(
          `Bookmark Launcher: failed to create "${this.filePath}". Check that the path is valid and the vault is writable.`
        );
      }
    }
    return f;
  }
  async parse() {
    const maxAttempts = 5;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      const f = this.getFile();
      if (!f) {
        if (attempt < maxAttempts - 1) {
          await sleep(300 * Math.pow(2, attempt));
          continue;
        }
        return { folders: [], uncategorized: [] };
      }
      const content = await this.app.vault.read(f);
      if (content === "" && f.stat.size > 0) {
        if (attempt < maxAttempts - 1) {
          await sleep(300 * Math.pow(2, attempt));
          continue;
        }
        return { folders: [], uncategorized: [] };
      }
      return this.parseContent(content);
    }
    return { folders: [], uncategorized: [] };
  }
  parseContent(content) {
    const lines = content.split("\n");
    const store = { folders: [], uncategorized: [] };
    let currentFolder = null;
    let currentSubfolder = null;
    for (const line of lines) {
      if (line.startsWith("## ")) {
        const name = line.slice(3).trim();
        if (currentFolder) {
          currentSubfolder = { name, bookmarks: [], subfolders: [] };
          currentFolder.subfolders.push(currentSubfolder);
        } else {
          currentSubfolder = null;
          currentFolder = { name, bookmarks: [], subfolders: [] };
          store.folders.push(currentFolder);
        }
      } else if (line.startsWith("# ")) {
        const name = line.slice(2).trim();
        currentSubfolder = null;
        currentFolder = { name, bookmarks: [], subfolders: [] };
        store.folders.push(currentFolder);
      } else {
        const m = line.match(BOOKMARK_RE);
        if (m) {
          const parsedUrl = m[2];
          if (!ALLOWED_SCHEMES.some((s) => parsedUrl.startsWith(s))) {
            continue;
          }
          const bm = { name: m[1], url: parsedUrl };
          if (currentSubfolder) {
            currentSubfolder.bookmarks.push(bm);
          } else if (currentFolder) {
            currentFolder.bookmarks.push(bm);
          } else {
            store.uncategorized.push(bm);
          }
        }
      }
    }
    return store;
  }
  serialize(store) {
    const parts = [];
    if (store.uncategorized.length > 0) {
      for (const bm of store.uncategorized) {
        parts.push(`- [${bm.name}](${bm.url})`);
      }
    }
    for (const folder of store.folders) {
      if (parts.length > 0)
        parts.push("");
      parts.push(`# ${folder.name}`);
      for (const bm of folder.bookmarks) {
        parts.push(`- [${bm.name}](${bm.url})`);
      }
      for (const sub of folder.subfolders) {
        parts.push("");
        parts.push(`## ${sub.name}`);
        for (const bm of sub.bookmarks) {
          parts.push(`- [${bm.name}](${bm.url})`);
        }
      }
    }
    return parts.join("\n") + "\n";
  }
  getFolderOptions(store) {
    const opts = [];
    for (const folder of store.folders) {
      opts.push({ label: folder.name, value: folder.name, isSubfolder: false });
      for (const sub of folder.subfolders) {
        opts.push({
          label: `  ${sub.name}`,
          value: `${folder.name}${FOLDER_SEP}${sub.name}`,
          isSubfolder: true
        });
      }
    }
    return opts;
  }
  async addBookmark(bookmark, targetFolderName, isNewFolder) {
    bookmark = { name: stripCtrl(bookmark.name), url: bookmark.url.replace(/[\x00-\x1f\x7f]/g, "").trim() };
    targetFolderName = stripCtrl(targetFolderName);
    const f = await this.ensureFile();
    await this.app.vault.process(f, (content) => {
      const store = this.parseContent(content);
      if (isNewFolder) {
        store.folders.push({
          name: targetFolderName,
          bookmarks: [bookmark],
          subfolders: []
        });
      } else if (!targetFolderName) {
        store.uncategorized.push(bookmark);
      } else {
        let added = false;
        const sepIdx = targetFolderName.indexOf(FOLDER_SEP);
        if (sepIdx !== -1) {
          const parentName = targetFolderName.slice(0, sepIdx);
          const subName = targetFolderName.slice(sepIdx + 1);
          for (const folder of store.folders) {
            if (folder.name === parentName) {
              const sub = folder.subfolders.find(
                (s) => s.name === subName
              );
              if (sub) {
                sub.bookmarks.push(bookmark);
                added = true;
              }
              break;
            }
          }
        } else {
          for (const folder of store.folders) {
            if (folder.name === targetFolderName) {
              folder.bookmarks.push(bookmark);
              added = true;
              break;
            }
          }
        }
        if (!added) {
          store.folders.push({
            name: targetFolderName,
            bookmarks: [bookmark],
            subfolders: []
          });
        }
      }
      return this.serialize(store);
    });
  }
};

// BookmarkView.ts
var import_obsidian2 = require("obsidian");

// i18n/en.json
var en_default = {
  "panel.title": "Navigator",
  "panel.empty": "No bookmarks yet. Press + to add one, or edit your bookmarks file directly.",
  "panel.loading": "Loading\u2026",
  "bookmark.add": "Add bookmark",
  "bookmark.settings": "Launchpad settings",
  "modal.heading": "Add bookmark",
  "modal.name.label": "Display name",
  "modal.name.placeholder": "e.g. Linear Board",
  "modal.name.error": "Name is required.",
  "modal.url.label": "URL",
  "modal.url.placeholder": "https://, obsidian://, vault://, note://, or [[note name]]",
  "modal.url.error": "URL must start with https://, http://, obsidian://, vault://, note://, or be [[note name]]",
  "modal.folder.label": "Target folder",
  "modal.folder.new": "+ New folder\u2026",
  "modal.folder.uncategorized": "Uncategorized",
  "modal.newFolder.label": "New folder name",
  "modal.newFolder.placeholder": "Folder name",
  "modal.save": "Save",
  "modal.cancel": "Cancel",
  "modal.saveError": "Failed to save. Please try again.",
  "back.ariaLabel": "Go back to",
  "tabs.folder": "Tabs",
  "tabs.empty": "No tabs open.",
  "tabs.ariaLabel": "Switch to tab",
  "latest.folder": "Latest",
  "latest.created": "Created",
  "latest.modified": "Modified",
  "latest.empty": "No files found.",
  "latest.ariaLabel": "Open file",
  "latest.delete.ariaLabel": "Delete file",
  "latest.delete.confirmTitle": "Delete file",
  "latest.delete.confirmMessage": 'Move "{filename}" to system trash?',
  "latest.delete.confirm": "Delete",
  "latest.delete.cancel": "Cancel",
  "settings.latestDelete.name": "Enable file deletion",
  "settings.latestDelete.desc": "Show a delete button on Latest items. Files are moved to the system trash."
};

// i18n/de.json
var de_default = {
  "panel.title": "Navigator",
  "panel.empty": "Noch keine Lesezeichen. Dr\xFCcke + um eines hinzuzuf\xFCgen oder bearbeite die Lesezeichen-Datei direkt.",
  "panel.loading": "Wird geladen\u2026",
  "bookmark.add": "Lesezeichen hinzuf\xFCgen",
  "bookmark.settings": "Launchpad-Einstellungen",
  "modal.heading": "Lesezeichen hinzuf\xFCgen",
  "modal.name.label": "Anzeigename",
  "modal.name.placeholder": "z. B. Linear Board",
  "modal.name.error": "Name ist erforderlich.",
  "modal.url.label": "URL",
  "modal.url.placeholder": "https://, obsidian://, vault://, note://, oder [[Notiztitel]]",
  "modal.url.error": "URL muss mit https://, http://, obsidian://, vault://, note:// beginnen oder [[Notiztitel]] sein.",
  "modal.folder.label": "Zielordner",
  "modal.folder.new": "+ Neuer Ordner\u2026",
  "modal.folder.uncategorized": "Ohne Kategorie",
  "modal.newFolder.label": "Name des neuen Ordners",
  "modal.newFolder.placeholder": "Ordnername",
  "modal.save": "Speichern",
  "modal.cancel": "Abbrechen",
  "modal.saveError": "Speichern fehlgeschlagen. Bitte erneut versuchen.",
  "back.ariaLabel": "Zur\xFCck zu",
  "tabs.folder": "Tabs",
  "tabs.empty": "Keine Tabs ge\xF6ffnet.",
  "tabs.ariaLabel": "Zu Tab wechseln",
  "latest.folder": "Zuletzt erstellt",
  "latest.created": "Erstellt",
  "latest.modified": "Zuletzt ge\xE4ndert",
  "latest.empty": "Keine Dateien gefunden.",
  "latest.ariaLabel": "Datei \xF6ffnen",
  "latest.delete.ariaLabel": "Datei l\xF6schen",
  "latest.delete.confirmTitle": "Datei l\xF6schen",
  "latest.delete.confirmMessage": '"{filename}" in den Papierkorb verschieben?',
  "latest.delete.confirm": "L\xF6schen",
  "latest.delete.cancel": "Abbrechen",
  "settings.latestDelete.name": "Datei l\xF6schen aktivieren",
  "settings.latestDelete.desc": "L\xF6schen-Schaltfl\xE4che bei zuletzt erstellten Dateien anzeigen. Dateien werden in den Papierkorb verschoben."
};

// i18n.ts
var enStrings = en_default;
var deStrings = de_default;
var locales = {
  en: enStrings,
  de: deStrings
};
function getLocale() {
  var _a2;
  return ((_a2 = window.localStorage.getItem("language")) != null ? _a2 : "en").slice(0, 2);
}
var locale = getLocale();
var _a;
var strings = (_a = locales[locale]) != null ? _a : enStrings;
function t(key) {
  return strings[key];
}

// BookmarkView.ts
function setIconWithFallback(element, primaryIcon, fallbackIcon) {
  try {
    (0, import_obsidian2.setIcon)(element, primaryIcon);
  } catch (e) {
    (0, import_obsidian2.setIcon)(element, fallbackIcon);
  }
}
var VIEW_TYPE_BOOKMARK = "launchpad-view";
var BookmarkView = class extends import_obsidian2.ItemView {
  constructor(leaf, host) {
    super(leaf);
    this.store = { folders: [], uncategorized: [] };
    this.host = host;
  }
  getViewType() {
    return VIEW_TYPE_BOOKMARK;
  }
  getDisplayText() {
    return "Launchpad";
  }
  getIcon() {
    return "rocket";
  }
  async onOpen() {
    this.render();
  }
  setStore(store) {
    this.store = store;
    this.render();
  }
  setLoading(isLoading) {
    if (isLoading) {
      this.contentEl.empty();
      this.contentEl.createDiv({ cls: "launchpad-loading", text: t("panel.loading") });
    }
  }
  /** Renders the full Launchpad panel from the current store snapshot and UI state. */
  render() {
    var _a2, _b;
    this.contentEl.empty();
    this.contentEl.addClass("launchpad-content-el");
    const containerEl = this.contentEl.createDiv("launchpad-container");
    containerEl.setAttribute("role", "navigation");
    containerEl.setAttribute("aria-label", "Launchpad");
    const headerEl = containerEl.createDiv("launchpad-header");
    headerEl.createSpan({ text: t("panel.title") });
    const settingsButtonEl = headerEl.createEl("button", {
      cls: "launchpad-settings-btn",
      attr: { "aria-label": t("bookmark.settings"), type: "button" }
    });
    (0, import_obsidian2.setIcon)(settingsButtonEl, "settings-2");
    settingsButtonEl.addEventListener("click", () => this.host.openSettings());
    const addButtonEl = headerEl.createEl("button", {
      cls: "launchpad-add-btn",
      attr: { "aria-label": t("bookmark.add"), type: "button" }
    });
    (0, import_obsidian2.setIcon)(addButtonEl, "plus-circle");
    addButtonEl.addEventListener("click", () => this.host.openCaptureModal());
    const scrollContainerEl = containerEl.createDiv("launchpad-scroll");
    const collapseState = this.host.getCollapseState();
    if (this.store.uncategorized.length > 0) {
      const uncategorizedSectionEl = scrollContainerEl.createDiv("launchpad-uncategorized");
      for (const bookmark of this.store.uncategorized) {
        this.renderBookmarkItem(uncategorizedSectionEl, bookmark.name, bookmark.url);
      }
    }
    for (const folder of this.store.folders) {
      this.renderFolder(scrollContainerEl, folder, collapseState, null);
    }
    if (this.store.folders.length === 0 && this.store.uncategorized.length === 0) {
      scrollContainerEl.createDiv({
        cls: "launchpad-empty",
        text: t("panel.empty")
      });
    }
    const openTabs = this.host.getOpenTabs();
    const tabsKey = "__tabs__";
    const tabsCollapsed = (_a2 = collapseState[tabsKey]) != null ? _a2 : false;
    const tabsFolderEl = scrollContainerEl.createDiv("launchpad-folder launchpad-tabs-folder");
    const tabsHeaderEl = tabsFolderEl.createEl("button", {
      cls: "launchpad-folder-header",
      attr: {
        type: "button",
        "aria-expanded": (!tabsCollapsed).toString()
      }
    });
    const tabsIconEl = tabsHeaderEl.createSpan({
      cls: "lp-folder-icon",
      attr: { "aria-hidden": "true" }
    });
    setIconWithFallback(tabsIconEl, "layout-grid", "layout-dashboard");
    tabsHeaderEl.createSpan({ text: t("tabs.folder") });
    const tabsArrow = tabsHeaderEl.createSpan({
      cls: "launchpad-folder-arrow" + (tabsCollapsed ? " collapsed" : ""),
      text: "\u25BE",
      attr: { "aria-hidden": "true" }
    });
    const tabsContentEl = tabsFolderEl.createDiv("launchpad-folder-content");
    if (tabsCollapsed)
      tabsContentEl.addClass("is-collapsed");
    const tabsInnerEl = tabsContentEl.createDiv("lp-inner");
    tabsHeaderEl.addEventListener("click", async () => {
      const nowCollapsed = !tabsContentEl.hasClass("is-collapsed");
      tabsContentEl.toggleClass("is-collapsed", nowCollapsed);
      tabsArrow.classList.toggle("collapsed", nowCollapsed);
      tabsHeaderEl.setAttribute("aria-expanded", (!nowCollapsed).toString());
      await this.host.setCollapseState(tabsKey, nowCollapsed);
    });
    if (openTabs.length === 0) {
      tabsInnerEl.createDiv({ cls: "launchpad-empty", text: t("tabs.empty") });
    } else {
      for (const tab of openTabs) {
        this.renderTabItem(tabsInnerEl, tab);
      }
    }
    const latestCreated = this.host.getLatestCreatedFiles();
    const latestModified = this.host.getLatestModifiedFiles();
    const latestKey = "__latest__";
    const latestCollapsed = (_b = collapseState[latestKey]) != null ? _b : false;
    const latestFolderEl = scrollContainerEl.createDiv("launchpad-folder launchpad-latest-folder");
    const latestHeaderEl = latestFolderEl.createEl("button", {
      cls: "launchpad-folder-header",
      attr: {
        type: "button",
        "aria-expanded": (!latestCollapsed).toString()
      }
    });
    const latestIconEl = latestHeaderEl.createSpan({
      cls: "lp-folder-icon",
      attr: { "aria-hidden": "true" }
    });
    setIconWithFallback(latestIconEl, "clock", "history");
    latestHeaderEl.createSpan({ text: t("latest.folder") });
    const latestArrow = latestHeaderEl.createSpan({
      cls: "launchpad-folder-arrow" + (latestCollapsed ? " collapsed" : ""),
      text: "\u25BE",
      attr: { "aria-hidden": "true" }
    });
    const latestContentEl = latestFolderEl.createDiv("launchpad-folder-content");
    if (latestCollapsed)
      latestContentEl.addClass("is-collapsed");
    const latestInnerEl = latestContentEl.createDiv("lp-inner");
    latestHeaderEl.addEventListener("click", async () => {
      const nowCollapsed = !latestContentEl.hasClass("is-collapsed");
      latestContentEl.toggleClass("is-collapsed", nowCollapsed);
      latestArrow.classList.toggle("collapsed", nowCollapsed);
      latestHeaderEl.setAttribute("aria-expanded", (!nowCollapsed).toString());
      await this.host.setCollapseState(latestKey, nowCollapsed);
    });
    this.renderLatestSubsection(
      latestInnerEl,
      collapseState,
      "__latest_created__",
      t("latest.created"),
      "file-plus",
      latestCreated
    );
    this.renderLatestSubsection(
      latestInnerEl,
      collapseState,
      "__latest_modified__",
      t("latest.modified"),
      "file-edit",
      latestModified
    );
    const previousFilename = this.host.getPreviousFilename();
    if (previousFilename !== null) {
      const backSectionEl = containerEl.createDiv("launchpad-back-section");
      const backLinkEl = backSectionEl.createEl("a", {
        cls: "launchpad-back-item",
        attr: { href: "#", title: `${t("back.ariaLabel")} ${previousFilename}` }
      });
      const backIconEl = backLinkEl.createSpan({ cls: "lp-item-icon", attr: { "aria-hidden": "true" } });
      (0, import_obsidian2.setIcon)(backIconEl, "arrow-left");
      backLinkEl.createSpan({ cls: "lp-item-name", text: previousFilename });
      backLinkEl.addEventListener("click", (e) => {
        e.preventDefault();
        this.host.navigateBack();
      });
    }
  }
  /** Renders a collapsible subsection inside the Latest folder. */
  renderLatestSubsection(containerEl, collapseState, subsectionKey, label, iconName, files) {
    var _a2;
    const isCollapsed = (_a2 = collapseState[subsectionKey]) != null ? _a2 : false;
    const subsectionEl = containerEl.createDiv("launchpad-subfolder");
    const subsectionHeaderEl = subsectionEl.createEl("button", {
      cls: "launchpad-subfolder-header",
      attr: {
        type: "button",
        "aria-expanded": (!isCollapsed).toString()
      }
    });
    const subsectionIconEl = subsectionHeaderEl.createSpan({
      cls: "lp-folder-icon",
      attr: { "aria-hidden": "true" }
    });
    setIconWithFallback(subsectionIconEl, iconName, "file-text");
    subsectionHeaderEl.createSpan({ text: label });
    const subsectionArrowEl = subsectionHeaderEl.createSpan({
      cls: "launchpad-folder-arrow" + (isCollapsed ? " collapsed" : ""),
      text: "\u25BE",
      attr: { "aria-hidden": "true" }
    });
    const subsectionContentEl = subsectionEl.createDiv("launchpad-subfolder-content");
    if (isCollapsed)
      subsectionContentEl.addClass("is-collapsed");
    const subsectionInnerEl = subsectionContentEl.createDiv("lp-inner");
    subsectionHeaderEl.addEventListener("click", async () => {
      const nowCollapsed = !subsectionContentEl.hasClass("is-collapsed");
      subsectionContentEl.toggleClass("is-collapsed", nowCollapsed);
      subsectionArrowEl.classList.toggle("collapsed", nowCollapsed);
      subsectionHeaderEl.setAttribute("aria-expanded", (!nowCollapsed).toString());
      await this.host.setCollapseState(subsectionKey, nowCollapsed);
    });
    if (files.length === 0) {
      subsectionInnerEl.createDiv({ cls: "launchpad-empty", text: t("latest.empty") });
    } else {
      for (const file of files) {
        this.renderLatestFileItem(subsectionInnerEl, file);
      }
    }
  }
  /** Renders a bookmark folder or subfolder branch with persisted collapse state. */
  renderFolder(containerEl, folder, collapseState, parentFolderName) {
    var _a2;
    const collapseKey = parentFolderName ? `${parentFolderName}${FOLDER_SEP}${folder.name}` : folder.name;
    const isCollapsed = (_a2 = collapseState[collapseKey]) != null ? _a2 : false;
    const folderEl = containerEl.createDiv(
      parentFolderName ? "launchpad-subfolder" : "launchpad-folder"
    );
    const headerClassName = parentFolderName ? "launchpad-subfolder-header" : "launchpad-folder-header";
    const headerEl = folderEl.createEl("button", {
      cls: headerClassName,
      attr: {
        type: "button",
        "aria-expanded": (!isCollapsed).toString()
      }
    });
    const folderIconEl = headerEl.createSpan({ cls: "lp-folder-icon", attr: { "aria-hidden": "true" } });
    (0, import_obsidian2.setIcon)(folderIconEl, "layers");
    headerEl.createSpan({ text: folder.name });
    const arrowEl = headerEl.createSpan({
      cls: "launchpad-folder-arrow" + (isCollapsed ? " collapsed" : ""),
      text: "\u25BE",
      attr: { "aria-hidden": "true" }
    });
    const contentEl = folderEl.createDiv(
      parentFolderName ? "launchpad-subfolder-content" : "launchpad-folder-content"
    );
    if (isCollapsed)
      contentEl.addClass("is-collapsed");
    const innerEl = contentEl.createDiv("lp-inner");
    headerEl.addEventListener("click", async () => {
      const nowCollapsed = !contentEl.hasClass("is-collapsed");
      contentEl.toggleClass("is-collapsed", nowCollapsed);
      arrowEl.classList.toggle("collapsed", nowCollapsed);
      headerEl.setAttribute("aria-expanded", (!nowCollapsed).toString());
      await this.host.setCollapseState(collapseKey, nowCollapsed);
    });
    for (const bookmark of folder.bookmarks) {
      this.renderBookmarkItem(innerEl, bookmark.name, bookmark.url);
    }
    for (const subfolder of folder.subfolders) {
      this.renderFolder(innerEl, subfolder, collapseState, folder.name);
    }
  }
  /** Renders one open-tab entry in the Tabs section. */
  renderTabItem(containerEl, tab) {
    const itemEl = containerEl.createEl("a", {
      cls: "launchpad-item launchpad-tab-item",
      attr: {
        href: "#",
        title: tab.title,
        "aria-label": `${t("tabs.ariaLabel")}: ${tab.title}`
      }
    });
    const iconEl = itemEl.createSpan({
      cls: "lp-item-icon",
      attr: { "aria-hidden": "true" }
    });
    const iconName = tab.type === "markdown" ? "file-text" : tab.type === "pdf" ? "file-type" : tab.type === "canvas" ? "layout-dashboard" : tab.type === "graph" ? "git-fork" : "file";
    (0, import_obsidian2.setIcon)(iconEl, iconName);
    itemEl.createSpan({ cls: "lp-item-name", text: tab.title });
    itemEl.addEventListener("click", (e) => {
      e.preventDefault();
      this.host.focusTab(tab.leafId);
    });
  }
  /** Renders one latest-file row including optional delete affordance. */
  renderLatestFileItem(containerEl, file) {
    const itemEl = containerEl.createEl("div", {
      cls: "launchpad-item launchpad-latest-item",
      attr: {
        title: file.path
      }
    });
    const fileLinkEl = itemEl.createEl("a", {
      cls: "launchpad-item-link",
      attr: {
        href: "#",
        "aria-label": `${t("latest.ariaLabel")}: ${file.title}`
      }
    });
    const iconEl = fileLinkEl.createSpan({
      cls: "lp-item-icon",
      attr: { "aria-hidden": "true" }
    });
    (0, import_obsidian2.setIcon)(iconEl, "file-text");
    fileLinkEl.createSpan({ cls: "lp-item-name", text: file.title });
    fileLinkEl.addEventListener("click", (e) => {
      e.preventDefault();
      this.host.openLatestFile(file.path);
    });
    if (this.host.isDeleteEnabled()) {
      const deleteButtonEl = itemEl.createEl("button", {
        cls: "launchpad-delete-btn",
        attr: {
          type: "button",
          "aria-label": `${t("latest.delete.ariaLabel")}: ${file.title}`
        }
      });
      const trashIconEl = deleteButtonEl.createSpan({
        attr: { "aria-hidden": "true" }
      });
      (0, import_obsidian2.setIcon)(trashIconEl, "trash-2");
      deleteButtonEl.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        new ConfirmDeleteModal(
          this.app,
          file.title,
          () => this.host.deleteLatestFile(file.path)
        ).open();
      });
    }
  }
  /** Renders one bookmark row in uncategorized, folder, or subfolder lists. */
  renderBookmarkItem(containerEl, name, url) {
    const itemEl = containerEl.createEl("a", {
      cls: "launchpad-item",
      attr: { href: "#", title: url }
    });
    const isVault = url.startsWith("vault://");
    const isNote = url.startsWith("note://");
    const isObsidian = url.startsWith("obsidian://");
    const itemIconEl = itemEl.createSpan({
      cls: isNote ? "lp-item-icon lp-item-icon--note" : isVault ? "lp-item-icon lp-item-icon--vault" : isObsidian ? "lp-item-icon lp-item-icon--obsidian" : "lp-item-icon",
      attr: { "aria-hidden": "true" }
    });
    const iconName = isNote || isObsidian ? "file-text" : (
      // file/note navigation
      isVault ? "library" : (
        // folder navigation
        "globe"
      )
    );
    (0, import_obsidian2.setIcon)(itemIconEl, iconName);
    itemEl.createSpan({ cls: "lp-item-name", text: name });
    itemEl.addEventListener("click", (e) => {
      e.preventDefault();
      this.host.openBookmarkUrl(url);
    });
  }
};
var ConfirmDeleteModal = class extends import_obsidian2.Modal {
  constructor(app, filename, onConfirm) {
    super(app);
    this.filename = filename;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("launchpad-confirm-modal");
    contentEl.createEl("h3", {
      text: t("latest.delete.confirmTitle")
    });
    contentEl.createEl("p", {
      text: t("latest.delete.confirmMessage").replace("{filename}", this.filename)
    });
    const actions = contentEl.createDiv("launchpad-capture-actions");
    const cancelBtn = actions.createEl("button", {
      attr: { type: "button" },
      text: t("latest.delete.cancel")
    });
    const confirmBtn = actions.createEl("button", {
      cls: "mod-warning",
      attr: { type: "button" },
      text: t("latest.delete.confirm")
    });
    cancelBtn.addEventListener("click", () => this.close());
    confirmBtn.addEventListener("click", () => {
      void Promise.resolve(this.onConfirm()).catch((error) => {
        console.error("Launchpad: failed to delete latest file", error);
      });
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// CaptureModal.ts
var import_obsidian3 = require("obsidian");
var NEW_FOLDER_VALUE = "__new__";
var UNCATEGORIZED_VALUE = "__uncategorized__";
var URL_PREFIXES = ["https://", "http://", "obsidian://", "vault://", "note://"];
function isAllowedUrl(value) {
  return URL_PREFIXES.some((prefix) => value.startsWith(prefix));
}
function isWikiLink(val) {
  if (!(val.startsWith("[[") && val.endsWith("]]")))
    return false;
  return val.slice(2, -2).trim().length > 0;
}
function normalizeUrl(val) {
  if (isWikiLink(val))
    return "note://" + val.slice(2, -2).trim();
  return val;
}
var CaptureModal = class extends import_obsidian3.Modal {
  constructor(app, store, getFolderOptions) {
    super(app);
    this.store = store;
    this.getFolderOptions = getFolderOptions;
  }
  onOpen() {
    const { contentEl } = this;
    const folderOptions = this.getFolderOptions();
    contentEl.addClass("launchpad-capture-modal");
    new import_obsidian3.Setting(contentEl).setName(t("modal.heading")).setHeading();
    let nameValue = "";
    let urlValue = "";
    let folderValue = folderOptions.length > 0 ? folderOptions[0].value : UNCATEGORIZED_VALUE;
    let newFolderValue = "";
    const nameField = contentEl.createDiv("launchpad-capture-field");
    const nameLbl = nameField.createEl("label", { text: t("modal.name.label") });
    nameLbl.setAttribute("for", "lp-cm-name");
    const nameInput = nameField.createEl("input", {
      attr: {
        id: "lp-cm-name",
        type: "text",
        placeholder: t("modal.name.placeholder"),
        "aria-describedby": "lp-cm-name-err"
      }
    });
    const nameErrorEl = nameField.createDiv({
      cls: "launchpad-capture-error",
      text: "",
      attr: { id: "lp-cm-name-err", "aria-live": "polite" }
    });
    const urlField = contentEl.createDiv("launchpad-capture-field");
    const urlLbl = urlField.createEl("label", { text: t("modal.url.label") });
    urlLbl.setAttribute("for", "lp-cm-url");
    const urlInput = urlField.createEl("input", {
      attr: {
        id: "lp-cm-url",
        type: "text",
        placeholder: t("modal.url.placeholder"),
        "aria-describedby": "lp-cm-url-err"
      }
    });
    const urlErrorEl = urlField.createDiv({
      cls: "launchpad-capture-error",
      text: "",
      attr: { id: "lp-cm-url-err", "aria-live": "polite" }
    });
    const folderField = contentEl.createDiv("launchpad-capture-field");
    const folderLbl = folderField.createEl("label", { text: t("modal.folder.label") });
    folderLbl.setAttribute("for", "lp-cm-folder");
    const folderSelect = folderField.createEl("select", {
      attr: { id: "lp-cm-folder" }
    });
    if (folderOptions.length === 0) {
      const opt = folderSelect.createEl("option", {
        text: t("modal.folder.uncategorized"),
        attr: { value: UNCATEGORIZED_VALUE }
      });
      opt.selected = true;
    } else {
      for (const opt of folderOptions) {
        folderSelect.createEl("option", {
          text: opt.label,
          attr: { value: opt.value }
        });
      }
    }
    folderSelect.createEl("option", {
      text: t("modal.folder.new"),
      attr: { value: NEW_FOLDER_VALUE }
    });
    const newFolderField = contentEl.createDiv("launchpad-capture-field launchpad-hidden");
    const newFolderLbl = newFolderField.createEl("label", { text: t("modal.newFolder.label") });
    newFolderLbl.setAttribute("for", "lp-cm-new-folder");
    const newFolderInput = newFolderField.createEl("input", {
      attr: { id: "lp-cm-new-folder", type: "text", placeholder: t("modal.newFolder.placeholder") }
    });
    folderSelect.addEventListener("change", () => {
      folderValue = folderSelect.value;
      newFolderField.toggleClass("launchpad-hidden", folderValue !== NEW_FOLDER_VALUE);
      updateSaveBtn();
    });
    newFolderInput.addEventListener("input", () => {
      newFolderValue = newFolderInput.value.trim();
      updateSaveBtn();
    });
    const actions = contentEl.createDiv("launchpad-capture-actions");
    const cancelBtn = actions.createEl("button", { text: t("modal.cancel") });
    const saveBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: t("modal.save")
    });
    const saveErrorEl = contentEl.createDiv({
      cls: "launchpad-capture-error",
      text: "",
      attr: { "aria-live": "polite" }
    });
    const updateSaveBtn = () => {
      const nameOk = nameValue.trim().length > 0;
      const urlOk = isAllowedUrl(urlValue.trim()) || isWikiLink(urlValue.trim());
      const folderOk = folderValue !== NEW_FOLDER_VALUE || newFolderValue.trim().length > 0;
      saveBtn.disabled = !(nameOk && urlOk && folderOk);
    };
    nameInput.addEventListener("input", () => {
      nameValue = nameInput.value;
      nameErrorEl.textContent = nameValue.trim().length === 0 ? t("modal.name.error") : "";
      updateSaveBtn();
    });
    urlInput.addEventListener("input", () => {
      urlValue = urlInput.value;
      const valid = isAllowedUrl(urlValue.trim()) || isWikiLink(urlValue.trim());
      urlErrorEl.textContent = valid ? "" : t("modal.url.error");
      updateSaveBtn();
    });
    cancelBtn.addEventListener("click", () => this.close());
    saveBtn.addEventListener("click", async () => {
      if (saveBtn.disabled)
        return;
      saveBtn.disabled = true;
      saveErrorEl.textContent = "";
      const name = nameValue.trim();
      const url = normalizeUrl(urlValue.trim());
      const isNew = folderValue === NEW_FOLDER_VALUE;
      const targetFolder = isNew ? newFolderValue.trim() : folderValue === UNCATEGORIZED_VALUE ? "" : folderValue;
      if (!name || !isAllowedUrl(url)) {
        saveBtn.disabled = false;
        return;
      }
      if (isNew && !targetFolder) {
        saveBtn.disabled = false;
        return;
      }
      try {
        const bm = { name, url };
        await this.store.addBookmark(bm, targetFolder, isNew);
        this.close();
      } catch (err) {
        saveBtn.disabled = false;
        console.error("Launchpad: failed to save bookmark", err);
        saveErrorEl.textContent = t("modal.saveError");
      }
    });
    updateSaveBtn();
    const handleKeydown = (e) => {
      if (e.key === "Enter" && !saveBtn.disabled) {
        saveBtn.click();
      }
    };
    nameInput.addEventListener("keydown", handleKeydown);
    urlInput.addEventListener("keydown", handleKeydown);
    newFolderInput.addEventListener("keydown", handleKeydown);
    nameInput.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// SetupModal.ts
var import_obsidian4 = require("obsidian");
var SetupModal = class extends import_obsidian4.Modal {
  constructor(app, onConfirm, currentPath) {
    super(app);
    this.onConfirm = onConfirm;
    this.currentPath = currentPath != null ? currentPath : null;
  }
  onOpen() {
    var _a2;
    const { contentEl } = this;
    const isReconfigure = this.currentPath !== null;
    contentEl.addClass("launchpad-setup-modal");
    new import_obsidian4.Setting(contentEl).setName(isReconfigure ? "Change bookmarks file" : "Set up Launchpad").setHeading();
    contentEl.createEl("p", {
      cls: "launchpad-setup-description",
      text: isReconfigure ? "Enter the vault-relative path of the Markdown file you want to use. The file will be created if it does not exist yet." : "Choose where to store your bookmarks file. You can place it anywhere inside your vault \u2014 it stays a plain Markdown file you can edit directly."
    });
    let pathValue = (_a2 = this.currentPath) != null ? _a2 : "bookmarks.md";
    const pathField = contentEl.createDiv("launchpad-capture-field");
    const pathLbl = pathField.createEl("label", { text: "File path (relative to vault root)" });
    pathLbl.setAttribute("for", "lp-sm-path");
    const pathInput = pathField.createEl("input", {
      attr: {
        id: "lp-sm-path",
        type: "text",
        placeholder: "bookmarks.md  or  Resources/bookmarks.md",
        "aria-describedby": "lp-sm-path-err"
      }
    });
    pathInput.value = pathValue;
    if (isReconfigure)
      pathInput.select();
    const errorEl = pathField.createDiv({
      cls: "launchpad-capture-error",
      text: "",
      attr: { id: "lp-sm-path-err", "aria-live": "polite" }
    });
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian4.TFolder && f.path !== "/").sort((a, b) => a.path.localeCompare(b.path)).slice(0, 8);
    if (folders.length > 0) {
      const hintRow = pathField.createDiv("launchpad-setup-hint");
      hintRow.createSpan({ cls: "launchpad-setup-hint-label", text: "Folders: " });
      for (const folder of folders) {
        const chip = hintRow.createEl("button", {
          cls: "launchpad-setup-chip",
          text: folder.path,
          attr: { type: "button" }
        });
        chip.addEventListener("click", () => {
          const filename = pathInput.value.trim().split("/").pop() || "bookmarks.md";
          pathInput.value = `${folder.path}/${filename}`;
          pathValue = pathInput.value;
          errorEl.textContent = validate(pathValue);
          confirmBtn.disabled = !!validate(pathValue);
          pathInput.focus();
        });
      }
    }
    const validate = (val) => {
      const v = val.trim();
      if (!v)
        return "Path is required.";
      if (!v.endsWith(".md"))
        return "File must end with .md";
      if (v.startsWith("/"))
        return "Use a relative path \u2014 no leading slash.";
      if (v.includes(".."))
        return "Path cannot contain ..";
      if (/[\x00-\x1f\x7f]/.test(v))
        return "Path contains invalid characters.";
      return "";
    };
    pathInput.addEventListener("input", () => {
      pathValue = pathInput.value;
      errorEl.textContent = validate(pathValue);
      confirmBtn.disabled = !!validate(pathValue);
    });
    const actions = contentEl.createDiv("launchpad-capture-actions");
    const cancelBtn = actions.createEl("button", { text: isReconfigure ? "Cancel" : "Later" });
    cancelBtn.addEventListener("click", () => this.close());
    const confirmLabel = isReconfigure ? "Save" : "Create file";
    const confirmBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: confirmLabel
    });
    confirmBtn.addEventListener("click", async () => {
      const err = validate(pathValue.trim());
      if (err) {
        errorEl.textContent = err;
        return;
      }
      confirmBtn.disabled = true;
      confirmBtn.setText(isReconfigure ? "Saving\u2026" : "Creating\u2026");
      try {
        await this.onConfirm((0, import_obsidian4.normalizePath)(pathValue.trim()));
        this.close();
      } catch (e) {
        errorEl.textContent = e instanceof Error ? e.message : String(e);
        confirmBtn.disabled = false;
        confirmBtn.setText(confirmLabel);
      }
    });
    pathInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !confirmBtn.disabled)
        confirmBtn.click();
    });
    pathInput.focus();
    pathInput.select();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// main.ts
var REFRESH_RETRY_MAX_ATTEMPTS = 6;
function sanitizePluginData(raw) {
  const data = raw && typeof raw === "object" ? raw : {};
  const collapseStateRaw = data.collapseState && typeof data.collapseState === "object" ? data.collapseState : {};
  const collapseState = {};
  for (const [key, value] of Object.entries(collapseStateRaw)) {
    if (typeof value === "boolean")
      collapseState[key] = value;
  }
  const bookmarksFilePath = typeof data.bookmarksFilePath === "string" ? data.bookmarksFilePath : null;
  const latestFilesCount = typeof data.latestFilesCount === "number" && Number.isInteger(data.latestFilesCount) && data.latestFilesCount > 0 ? data.latestFilesCount : DEFAULT_DATA.latestFilesCount;
  const latestDeleteEnabled = typeof data.latestDeleteEnabled === "boolean" ? data.latestDeleteEnabled : DEFAULT_DATA.latestDeleteEnabled;
  return {
    collapseState,
    bookmarksFilePath,
    latestFilesCount,
    latestDeleteEnabled
  };
}
var DEFAULT_DATA = {
  collapseState: {},
  bookmarksFilePath: null,
  latestFilesCount: 5,
  latestDeleteEnabled: false
};
var LaunchpadPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    /** File that was active immediately before an obsidian:// bookmark click. */
    this.previousFile = null;
    /** Pending exponential-backoff retry for refreshViews when iCloud read fails. */
    this.refreshRetryTimer = null;
    /** Debounce timer for workspace-event-triggered refreshes. */
    this.refreshDebounceTimer = null;
    this.refreshRequestId = 0;
  }
  async onload() {
    var _a2;
    this.data = sanitizePluginData(await this.loadData());
    this.store = new BookmarkStoreManager(
      this.app,
      (_a2 = this.data.bookmarksFilePath) != null ? _a2 : DEFAULT_BOOKMARKS_FILE
    );
    this.registerView(VIEW_TYPE_BOOKMARK, (leaf) => new BookmarkView(leaf, this));
    this.addRibbonIcon("bookmark", "Launchpad", () => this.revealPanel());
    this.addCommand({
      id: "add-bookmark",
      name: "Add bookmark",
      callback: () => this.openCaptureModal()
    });
    this.addCommand({
      id: "open-panel",
      name: "Open panel",
      callback: () => this.revealPanel()
    });
    this.addCommand({
      id: "configure-file",
      name: "Configure bookmarks file location",
      callback: () => this.showSetupModal()
    });
    this.addSettingTab(new LaunchpadSettingTab(this.app, this));
    const onBookmarksFileModify = (file) => {
      if (file instanceof import_obsidian5.TFile && file.path === this.store.getFilePath())
        this.refreshViews();
    };
    this.registerEvent(this.app.vault.on("modify", onBookmarksFileModify));
    const onBookmarksFileCreate = (file) => {
      if (file instanceof import_obsidian5.TFile && file.path === this.store.getFilePath())
        this.refreshViews();
    };
    this.registerEvent(this.app.vault.on("create", onBookmarksFileCreate));
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        const path = this.store.getFilePath();
        if (file instanceof import_obsidian5.TFile && (file.path === path || oldPath === path)) {
          this.refreshViews();
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian5.TFolder))
          return;
        const launchpadPath = "vault://" + file.path.split("/").map(encodeURIComponent).join("/");
        menu.addItem(
          (item) => item.setTitle("Copy path for Launchpad").setIcon("copy").setSection("info").onClick(() => navigator.clipboard.writeText(launchpadPath))
        );
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.debouncedRefresh())
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if ((leaf == null ? void 0 : leaf.view.getViewType()) === VIEW_TYPE_BOOKMARK)
          return;
        this.debouncedRefresh();
      })
    );
    this.app.workspace.onLayoutReady(() => this.initOnReady());
  }
  async onunload() {
    if (this.refreshRetryTimer !== null) {
      window.clearTimeout(this.refreshRetryTimer);
      this.refreshRetryTimer = null;
    }
    if (this.refreshDebounceTimer !== null) {
      window.clearTimeout(this.refreshDebounceTimer);
      this.refreshDebounceTimer = null;
    }
  }
  debouncedRefresh(delayMs = 150) {
    if (this.refreshDebounceTimer !== null) {
      window.clearTimeout(this.refreshDebounceTimer);
    }
    this.refreshDebounceTimer = window.setTimeout(() => {
      this.refreshDebounceTimer = null;
      this.refreshViews();
    }, delayMs);
  }
  // ── Startup ────────────────────────────────────────────────────────────
  async initOnReady() {
    if (this.data.bookmarksFilePath) {
      await this.openAndRefresh();
      return;
    }
    const legacyFile = this.app.vault.getAbstractFileByPath(DEFAULT_BOOKMARKS_FILE);
    if (legacyFile instanceof import_obsidian5.TFile) {
      await this.adoptPath(DEFAULT_BOOKMARKS_FILE);
      await this.openAndRefresh();
      return;
    }
    this.showSetupModal();
  }
  /** Ensures the sidebar panel is open and populated. */
  async openAndRefresh() {
    await this.ensurePanelOpen();
    await this.refreshViews();
  }
  /** Adds the panel to the right sidebar if it is not already there. */
  async ensurePanelOpen() {
    var _a2;
    if (this.app.workspace.getLeavesOfType(VIEW_TYPE_BOOKMARK).length > 0) {
      return;
    }
    const leaf = (_a2 = this.app.workspace.getRightLeaf(false)) != null ? _a2 : this.app.workspace.getRightLeaf(true);
    if (!leaf)
      return;
    await leaf.setViewState({ type: VIEW_TYPE_BOOKMARK, active: true });
  }
  // ── Setup modal ────────────────────────────────────────────────────────
  showSetupModal() {
    new SetupModal(
      this.app,
      async (chosenPath) => {
        await this.adoptPath(chosenPath);
        await this.store.ensureFile();
        await this.revealPanel();
      },
      this.data.bookmarksFilePath
    ).open();
  }
  /** Called from the sidebar gear button — implements BookmarkViewHost. */
  openSetupModal() {
    this.showSetupModal();
  }
  /** Opens Obsidian's settings modal on this plugin's settings tab. */
  openSettings() {
    const settingsApi = this.app.setting;
    if (!settingsApi)
      return;
    settingsApi.open();
    settingsApi.openTabById(this.manifest.id);
  }
  /** Persist a confirmed bookmarks file path and point the store at it. */
  async adoptPath(path) {
    this.data.bookmarksFilePath = path;
    await this.saveSettings();
    this.store.setFilePath(path);
  }
  get settings() {
    return this.data;
  }
  async saveSettings() {
    await this.saveData(this.data);
  }
  // ── BookmarkViewHost ───────────────────────────────────────────────────
  async openCaptureModal() {
    const storeData = await this.store.parse();
    new CaptureModal(
      this.app,
      this.store,
      () => this.store.getFolderOptions(storeData)
    ).open();
  }
  getCollapseState() {
    return this.data.collapseState;
  }
  async setCollapseState(key, collapsed) {
    this.data.collapseState[key] = collapsed;
    await this.saveSettings();
  }
  openBookmarkUrl(url) {
    if (/[\x00-\x1f\x7f]/.test(url)) {
      new import_obsidian5.Notice("Launchpad: URL contains invalid characters and was not opened.");
      return;
    }
    if (url.startsWith("vault://")) {
      let folderPath = "";
      try {
        folderPath = decodeURIComponent(url.slice("vault://".length));
      } catch (e) {
        new import_obsidian5.Notice("Launchpad: invalid vault path encoding.");
        return;
      }
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (!(folder instanceof import_obsidian5.TFolder)) {
        new import_obsidian5.Notice(`Launchpad: folder not found \u2014 ${folderPath}`);
        return;
      }
      const leaves = this.app.workspace.getLeavesOfType("file-explorer");
      if (leaves.length > 0) {
        try {
          this.app.workspace.revealLeaf(leaves[0]);
          const view = leaves[0].view;
          if (typeof view.revealInFolder === "function") {
            view.revealInFolder(folder);
            return;
          }
        } catch (e) {
        }
      }
      new import_obsidian5.Notice(`Launchpad: ${folderPath}`);
    } else if (url.startsWith("note://")) {
      const notePath = url.slice("note://".length);
      const file = this.app.metadataCache.getFirstLinkpathDest(notePath, "");
      if (!file) {
        new import_obsidian5.Notice(`Launchpad: note not found \u2014 ${notePath}`);
        return;
      }
      void this.app.workspace.getLeaf(false).openFile(file);
    } else if (url.startsWith("obsidian://")) {
      this.previousFile = this.app.workspace.getActiveFile();
      window.open(url);
      void this.refreshViews();
    } else if (url.startsWith("https://") || url.startsWith("http://")) {
      window.open(url, "_blank", "noopener,noreferrer");
    }
  }
  getPreviousFilename() {
    var _a2, _b;
    return (_b = (_a2 = this.previousFile) == null ? void 0 : _a2.basename) != null ? _b : null;
  }
  async navigateBack() {
    const file = this.previousFile;
    if (!file)
      return;
    this.previousFile = null;
    if (!(this.app.vault.getAbstractFileByPath(file.path) instanceof import_obsidian5.TFile)) {
      await this.refreshViews();
      return;
    }
    await this.app.workspace.getLeaf(false).openFile(file);
    await this.refreshViews();
  }
  getOpenTabs() {
    const tabs = [];
    const workspacePrivate = this.app.workspace;
    const root = workspacePrivate.rootSplit;
    const iterateLeaves = workspacePrivate.iterateLeaves;
    if (!iterateLeaves || !root)
      return tabs;
    iterateLeaves((leaf) => {
      if (leaf.view.getViewType() === VIEW_TYPE_BOOKMARK)
        return;
      if (!leaf.id)
        return;
      tabs.push({
        title: leaf.view.getDisplayText(),
        type: leaf.view.getViewType(),
        leafId: leaf.id
      });
    }, root);
    return tabs;
  }
  getLatestCreatedFiles() {
    return this.app.vault.getFiles().sort((a, b) => b.stat.ctime - a.stat.ctime).slice(0, this.settings.latestFilesCount).map((file) => ({
      title: file.basename,
      path: file.path,
      ctime: file.stat.ctime
    }));
  }
  getLatestModifiedFiles() {
    const createdPaths = new Set(
      this.getLatestCreatedFiles().map((f) => f.path)
    );
    return this.app.vault.getFiles().filter((file) => !createdPaths.has(file.path)).sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, this.settings.latestFilesCount).map((file) => ({
      title: file.basename,
      path: file.path,
      ctime: file.stat.mtime
    }));
  }
  openLatestFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian5.TFile) {
      void this.app.workspace.getLeaf(false).openFile(file);
    }
  }
  async deleteLatestFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian5.TFile) {
      await this.app.vault.trash(file, true);
      await this.refreshViews();
    }
  }
  isDeleteEnabled() {
    return this.settings.latestDeleteEnabled;
  }
  focusTab(leafId) {
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf.id === leafId) {
        this.app.workspace.setActiveLeaf(leaf, { focus: true });
      }
    });
  }
  // ── Panel management ───────────────────────────────────────────────────
  async revealPanel() {
    var _a2;
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_BOOKMARK);
    if (existing.length > 0) {
      const leaf = existing[0];
      this.app.workspace.setActiveLeaf(leaf, { focus: true });
      this.app.workspace.revealLeaf(leaf);
    } else {
      const leaf = (_a2 = this.app.workspace.getRightLeaf(false)) != null ? _a2 : this.app.workspace.getRightLeaf(true);
      if (!leaf)
        return;
      await leaf.setViewState({ type: VIEW_TYPE_BOOKMARK, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
    await this.refreshViews();
  }
  async refreshViews(retryCount = 0) {
    const requestId = ++this.refreshRequestId;
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_BOOKMARK);
    if (leaves.length === 0)
      return;
    for (const leaf of leaves) {
      if (leaf.view instanceof BookmarkView) {
        leaf.view.setLoading(true);
      }
    }
    let storeData;
    try {
      storeData = await this.store.parse();
    } catch (e) {
      if (retryCount < REFRESH_RETRY_MAX_ATTEMPTS) {
        if (this.refreshRetryTimer !== null) {
          window.clearTimeout(this.refreshRetryTimer);
        }
        this.refreshRetryTimer = window.setTimeout(
          () => this.refreshViews(retryCount + 1),
          1e3 * Math.pow(2, retryCount)
        );
      }
      return;
    }
    if (requestId !== this.refreshRequestId) {
      return;
    }
    if (this.refreshRetryTimer !== null) {
      window.clearTimeout(this.refreshRetryTimer);
      this.refreshRetryTimer = null;
    }
    for (const leaf of leaves) {
      if (leaf.view instanceof BookmarkView) {
        leaf.view.setStore(storeData);
      }
    }
  }
};
var LaunchpadSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian5.Setting(containerEl).setName("Latest files count").setDesc("Number of recently created files to show in the Latest section.").addText(
      (text) => text.setPlaceholder("5").setValue(String(this.plugin.settings.latestFilesCount)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.latestFilesCount = n;
          await this.plugin.saveSettings();
          await this.plugin.refreshViews();
        }
      })
    );
    new import_obsidian5.Setting(containerEl).setName(t("settings.latestDelete.name")).setDesc(t("settings.latestDelete.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.latestDeleteEnabled).onChange(async (value) => {
        this.plugin.settings.latestDeleteEnabled = value;
        await this.plugin.saveSettings();
        await this.plugin.refreshViews();
      })
    );
  }
};
